# Generated by Django 3.0.8 on 2021-07-04 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_user_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follow',
            field=models.ManyToManyField(related_name='_user_follow_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
